// <auto-generated />
using System;
using ClusterSalesManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClusterSalesManagementSystem.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260414053915_ClusterCreateAndSales")]
    partial class ClusterCreateAndSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClusterSalesManagementSystem.Models.Cluster", b =>
                {
                    b.Property<decimal>("CluId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("CluId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("CluId"));

                    b.Property<string>("CluName")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("CluName");

                    b.HasKey("CluId");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("ClusterSalesManagementSystem.Models.Sales", b =>
                {
                    b.Property<decimal>("SalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("SalesId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("SalesId"));

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("InvoiceUrl");

                    b.Property<decimal>("SalesAmount")
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("SalesAmount");

                    b.Property<decimal>("SalesCluId")
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("SalesCluId");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SalesId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ClusterSalesManagementSystem.Models.User", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UserId"));

                    b.Property<string>("PasswordHash")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserPassword");

                    b.Property<string>("UserName")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("UserRole")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserRole");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
