// <auto-generated />
using ClusterSalesManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClusterSalesManagementSystem.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260414053551_AllTableCreate")]
    partial class AllTableCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClusterSalesManagementSystem.Models.User", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Numeric(18,0)")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("UserId"));

                    b.Property<string>("PasswordHash")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserPassword");

                    b.Property<string>("UserName")
                        .HasColumnType("Nvarchar(100)");

                    b.Property<string>("UserRole")
                        .HasColumnType("Nvarchar(100)")
                        .HasColumnName("UserRole");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
